import AppKit

protocol PasteboardReading: AnyObject {
    var changeCount: Int { get }
    func string() -> String?
    func types() -> [String]
    /// Raw data for the given UTI. Returns nil if absent.
    func data(forType type: String) -> Data?
    /// File URLs from a `.fileURL` pasteboard. Returns empty if none.
    func fileURLs() -> [URL]
    /// Back up all pasteboard items by copying their raw types and data.
    func copyItems() -> [NSPasteboardItem]?
    /// Restore the copied pasteboard items.
    @discardableResult
    func writeItems(_ items: [NSPasteboardItem]) -> Int
}

final class SystemPasteboard: PasteboardReading {
    private let pasteboard = NSPasteboard.general

    var changeCount: Int { pasteboard.changeCount }

    func string() -> String? {
        pasteboard.string(forType: .string)
    }

    func types() -> [String] {
        pasteboard.types?.map(\.rawValue) ?? []
    }

    func data(forType type: String) -> Data? {
        pasteboard.data(forType: NSPasteboard.PasteboardType(type))
    }

    func fileURLs() -> [URL] {
        guard
            let objs = pasteboard.readObjects(
                forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL]
        else {
            return []
        }
        return objs
    }

    func copyItems() -> [NSPasteboardItem]? {
        return pasteboard.pasteboardItems?.map { item in
            let newItem = NSPasteboardItem()
            for type in item.types {
                if let data = item.data(forType: type) {
                    newItem.setData(data, forType: type)
                }
            }
            return newItem
        }
    }

    @discardableResult
    func writeItems(_ items: [NSPasteboardItem]) -> Int {
        pasteboard.clearContents()
        pasteboard.writeObjects(items)
        return pasteboard.changeCount
    }

    /// Writer used by ClipboardController. Returns the new changeCount after the write.
    @discardableResult
    func write(_ text: String) -> Int {
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        return pasteboard.changeCount
    }

    /// Writes one or more typed payloads atomically. Returns the new changeCount.
    @discardableResult
    func write(payloads: [(type: String, data: Data)]) -> Int {
        pasteboard.clearContents()
        for p in payloads {
            pasteboard.setData(p.data, forType: NSPasteboard.PasteboardType(p.type))
        }
        return pasteboard.changeCount
    }

    /// Writes a single file URL. Returns the new changeCount.
    @discardableResult
    func write(fileURL: URL) -> Int {
        pasteboard.clearContents()
        _ = pasteboard.writeObjects([fileURL as NSURL])
        return pasteboard.changeCount
    }

    @discardableResult
    func clear() -> Int {
        pasteboard.clearContents()
        return pasteboard.changeCount
    }
}

enum ConfidentialClipboardType {
    static let concealed = "org.nspasteboard.ConcealedType"
    static let transient = "org.nspasteboard.TransientType"
    static let autoGenerated = "org.nspasteboard.AutoGeneratedType"

    static let all: Set<String> = [concealed, transient, autoGenerated]
}
