import AppKit

protocol PasteboardReading: AnyObject {
    var changeCount: Int { get }
    func string() -> String?
    func types() -> [String]
}

final class SystemPasteboard: PasteboardReading {
    private let pasteboard = NSPasteboard.general

    var changeCount: Int { pasteboard.changeCount }

    func string() -> String? {
        pasteboard.string(forType: .string)
    }

    func types() -> [String] {
        pasteboard.types?.map(\.rawValue) ?? []
    }

    /// Writer used by ClipboardController. Returns the new changeCount after the write.
    @discardableResult
    func write(_ text: String) -> Int {
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        return pasteboard.changeCount
    }

    func clear() {
        pasteboard.clearContents()
    }
}

enum ConfidentialClipboardType {
    static let concealed = "org.nspasteboard.ConcealedType"
    static let transient = "org.nspasteboard.TransientType"
    static let autoGenerated = "org.nspasteboard.AutoGeneratedType"

    static let all: Set<String> = [concealed, transient, autoGenerated]
}
